export interface MedulaOsea {
  id: number,
  pacienteId: number,
  dolorPersistenteHuesos: string,
  dolorPersistenteAbdomen: string,
  fiebrePersistente: string,
  moretones: string,
  sangradoNarizEncias: string,
  crecimientoTumoral: string,
  inflamacionGanglios: string,
  picazonCorporal: string,
  cansancioFacil: string,
  palidez: string,
  anemiaSubita: string,
  perdidaPeso: string,
  dolorCabeza: string,
  vomitosMatutinos: string,
  crecimientoRapidoAbdomen: string,
}
