export interface SangrePeriferica {
  id: number,
  pacienteId: number,
  linfoblastoBPatologico: number,
  blastoMieloide: number,
  linfoblastoBNormal: number,
  linfBMaduroEinterm: number,
  linfocitosT: number,
  celulasNK: number,
  serieGranulocitoNeutrofilo: number,
  serieMonocritica: number,
  eosinofilo: number,
  basofiloCD: number,
  serieEritroide: number,
  plasmocito: number,
  celularidad: number,
}
