export interface SangrePeriferica {
  id: number,
  pacienteId: number,
  hemoglobina: number,
  hematocrito: number,
  hematies: number,
  volumenCorpuscularMedio: number,
  hemoglobinaCorpuscularMedia: number,
  concentracionHemoglobinaCorpuscular: number,
  indiceAnisocitosisRDW: number,
  indiceAnisocitosisRDWSD: number,
  leucocitosTotales: number,
  eosinofilosP: number,
  basofilosP: number,
  linfocitosP: number,
  monocitosP: number,
  neutrofilosSegmentadosP: number,
  bastonesP: number,
  eosinofilosD: number,
  basofilosD: number,
  linfocitosD: number,
  monocitosD: number,
  neutrofilosSegmentadosD: number,
  bastonesD: number,
  recuentoPlaqueta: number,
  volumenPlaquetarioMedio: number,
}
